import { createHash, randomBytes } from "node:crypto";
import { openEtsyOAuthState, readEtsyTokenEncryptionKey, sealEtsyOAuthState } from "./etsy-token-crypto.js";
import { updateEtsyTokens } from "./etsy-connection-store.js";

const AUTHORIZE_URL = "https://www.etsy.com/oauth/connect";
const TOKEN_URL = "https://api.etsy.com/v3/public/oauth/token";
export const ETSY_SCOPES = "transactions_r shops_r";
export const OAUTH_STATE_MAX_AGE_SECONDS = 900;
export const ETSY_REQUEST_TIMEOUT_MS = 15000;
export const REFRESH_TOKEN_LIFETIME_MS = 90 * 86400000;
export class EtsyConnectionError extends Error { constructor(message = "Unable to connect Etsy shop.", options = {}) { super(message, options); this.name = "EtsyConnectionError"; } }
function config(env = process.env) { const keystring = env.ETSY_API_KEY_KEYSTRING, sharedSecret = env.ETSY_API_SHARED_SECRET, redirectUri = env.ETSY_REDIRECT_URI; if (!keystring || !sharedSecret || !redirectUri) throw new EtsyConnectionError(); return { keystring, redirectUri, xApiKey: `${keystring}:${sharedSecret}` }; }
function normalizeToken(payload, now) { if (!payload?.access_token || !payload?.refresh_token) throw new EtsyConnectionError(); const seconds = Number(payload.expires_in); return { accessToken: payload.access_token, refreshToken: payload.refresh_token, accessTokenExpiresAt: new Date(now.getTime() + (Number.isFinite(seconds) ? seconds : 3600) * 1000).toISOString(), refreshTokenExpiresAt: new Date(now.getTime() + REFRESH_TOKEN_LIFETIME_MS).toISOString() }; }
async function tokenRequest(params, { env = process.env, fetchImpl = fetch, now = new Date(), createTimeoutSignal = () => AbortSignal.timeout(ETSY_REQUEST_TIMEOUT_MS) } = {}) { const { xApiKey } = config(env); try { const response = await fetchImpl(TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", "x-api-key": xApiKey }, body: new URLSearchParams(params), signal: createTimeoutSignal() }); if (!response.ok) throw new Error("failed"); return normalizeToken(await response.json(), now); } catch (error) { throw new EtsyConnectionError(undefined, { cause: error }); } }
export function beginEtsyAuthorization({ workspaceId, userId, env = process.env, now = new Date(), encryptionKey = readEtsyTokenEncryptionKey(env) }) { const { keystring, redirectUri } = config(env), verifier = randomBytes(64).toString("base64url"), state = randomBytes(48).toString("base64url"), challenge = createHash("sha256").update(verifier).digest("base64url"); const sealedContext = sealEtsyOAuthState({ state, verifier, workspaceId, userId, issuedAt: now.toISOString() }, encryptionKey); const query = new URLSearchParams({ response_type: "code", redirect_uri: redirectUri, scope: ETSY_SCOPES, client_id: keystring, state, code_challenge: challenge, code_challenge_method: "S256" }); return { authorizeUrl: `${AUTHORIZE_URL}?${query}`, sealedContext, state, verifier, challenge }; }
export function openEtsyAuthorizationContext({ sealedContext, returnedState, workspaceId, userId, env = process.env, now = new Date(), encryptionKey = readEtsyTokenEncryptionKey(env) }) { let context; try { context = openEtsyOAuthState(sealedContext, encryptionKey); } catch { throw new EtsyConnectionError(); } const issued = Date.parse(context.issuedAt); if (!returnedState || context.state !== returnedState || context.workspaceId !== workspaceId || context.userId !== userId || !Number.isFinite(issued) || now.getTime() < issued || now.getTime() - issued > OAUTH_STATE_MAX_AGE_SECONDS * 1000) throw new EtsyConnectionError(); return context; }
export function exchangeEtsyCallback({ code, verifier, env, fetchImpl, now, createTimeoutSignal }) { const { keystring, redirectUri } = config(env); return tokenRequest({ grant_type: "authorization_code", client_id: keystring, redirect_uri: redirectUri, code, code_verifier: verifier }, { env, fetchImpl, now, createTimeoutSignal }); }
export async function refreshEtsyAuthorization({ workspaceId, refreshToken, env, fetchImpl, now = new Date(), persist = true, createTimeoutSignal }) { const { keystring } = config(env), tokens = await tokenRequest({ grant_type: "refresh_token", client_id: keystring, refresh_token: refreshToken }, { env, fetchImpl, now, createTimeoutSignal }); if (persist) { const connection = await updateEtsyTokens({ workspaceId, ...tokens }); if (!connection) throw new EtsyConnectionError(); } return tokens; }
