import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ open: vi.fn(), key: vi.fn(), validate: vi.fn(), exchange: vi.fn(), save: vi.fn() }));
vi.mock("../../api/_lib/etsy-token-crypto.js", () => ({ openEtsyOAuthState: mocks.open, readEtsyTokenEncryptionKey: mocks.key }));
vi.mock("../../api/_lib/etsy-oauth.js", () => ({ openEtsyAuthorizationContext: mocks.validate, exchangeEtsyCallback: mocks.exchange }));
vi.mock("../../api/_lib/etsy-connection-store.js", () => ({ saveEtsyConnection: mocks.save }));
import handler from "../../api/etsy-callback.js";
function response() { return { headers: {}, status(v) { this.statusCode = v; return this; }, setHeader(k, v) { this.headers[k] = v; }, redirect(v) { this.location = v; }, json(v) { this.body = v; } }; }
beforeEach(() => { Object.values(mocks).forEach((mock) => mock.mockReset()); mocks.key.mockReturnValue(Buffer.alloc(32)); mocks.open.mockReturnValue({ workspaceId: "w", userId: "u" }); mocks.validate.mockReturnValue({ workspaceId: "w", userId: "u", verifier: "v" }); mocks.exchange.mockResolvedValue({ accessToken: "123.access", refreshToken: "refresh", accessTokenExpiresAt: "a", refreshTokenExpiresAt: "r" }); mocks.save.mockResolvedValue({}); vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: true, json: async () => ({ results: [{ shop_id: 44, shop_name: "Shop" }] }) })); });
describe("Etsy callback API", () => {
  it("validates binding, saves shop and redirects", async () => { const res = response(); await handler({ method: "GET", headers: { cookie: "etsy_oauth=sealed" }, query: { code: "code", state: "state" } }, res); expect(mocks.validate).toHaveBeenCalledWith(expect.objectContaining({ workspaceId: "w", userId: "u", returnedState: "state" })); expect(mocks.save).toHaveBeenCalledWith(expect.objectContaining({ etsyUserId: "123", etsyShopId: "44" })); expect(fetch.mock.calls[0][1].signal).toBeDefined(); expect(res.location).toBe("/orders?etsy=connected"); expect(res.headers["Set-Cookie"]).toContain("Max-Age=0"); expect(res.headers["Cache-Control"]).toBe("no-store"); });
  it("uses generic error redirect and clears cookie", async () => { mocks.validate.mockImplementation(() => { throw new Error("secret-token"); }); vi.spyOn(console, "error").mockImplementation(() => {}); const res = response(); await handler({ method: "GET", headers: { cookie: "etsy_oauth=sealed" }, query: { code: "secret-code", state: "bad" } }, res); expect(res.location).toBe("/orders?etsy=connection-error"); expect(JSON.stringify(res)).not.toContain("secret"); });
  it.each([
    [{ method: "GET", headers: {}, query: { code: "code", state: "state" } }, "missing cookie"],
    [{ method: "GET", headers: { cookie: "etsy_oauth=sealed" }, query: { state: "state" } }, "missing code"],
    [{ method: "GET", headers: { cookie: "etsy_oauth=sealed" }, query: { code: "code" } }, "missing state"],
    [{ method: "POST", headers: { cookie: "etsy_oauth=sealed" }, query: { code: "code", state: "state" } }, "non-GET"],
  ])("clears cookie and redirects for %s", async (req) => { vi.spyOn(console, "error").mockImplementation(() => {}); const res = response(); await handler(req, res); expect(res.location).toBe("/orders?etsy=connection-error"); expect(res.headers["Set-Cookie"]).toContain("Max-Age=0"); });
  it("rejects a nonnumeric access-token prefix generically", async () => { mocks.exchange.mockResolvedValue({ accessToken: "not-a-user.access", refreshToken: "r" }); vi.spyOn(console, "error").mockImplementation(() => {}); const res = response(); await handler({ method: "GET", headers: { cookie: "etsy_oauth=sealed" }, query: { code: "code", state: "state" } }, res); expect(res.location).toBe("/orders?etsy=connection-error"); expect(mocks.save).not.toHaveBeenCalled(); });
  it.each([{ results: [] }, {}])("rejects an empty or invalid shop response", async (shopPayload) => { fetch.mockResolvedValueOnce({ ok: true, json: async () => shopPayload }); vi.spyOn(console, "error").mockImplementation(() => {}); const res = response(); await handler({ method: "GET", headers: { cookie: "etsy_oauth=sealed" }, query: { code: "code", state: "state" } }, res); expect(res.location).toBe("/orders?etsy=connection-error"); expect(mocks.save).not.toHaveBeenCalled(); });  it("maps seller-shop lookup aborts to the generic redirect without secrets", async () => { fetch.mockRejectedValueOnce(Object.assign(new Error("secret shop timeout"), { name: "AbortError" })); const spy = vi.spyOn(console, "error").mockImplementation(() => {}); const res = response(); await handler({ method: "GET", headers: { cookie: "etsy_oauth=sealed" }, query: { code: "secret-code", state: "state" } }, res); expect(res.location).toBe("/orders?etsy=connection-error"); expect(res.headers["Set-Cookie"]).toContain("Max-Age=0"); expect(JSON.stringify(res)).not.toContain("secret"); expect(spy).toHaveBeenCalledWith("Etsy callback error", "AbortError"); });});
