import { createHash } from "node:crypto";
import { describe, expect, it, vi } from "vitest";
import { beginEtsyAuthorization, exchangeEtsyCallback, openEtsyAuthorizationContext, refreshEtsyAuthorization } from "../../api/_lib/etsy-oauth.js";
const store = vi.hoisted(() => ({ update: vi.fn() }));
vi.mock("../../api/_lib/etsy-connection-store.js", () => ({ updateEtsyTokens: store.update }));
const env = { ETSY_API_KEY_KEYSTRING: "key", ETSY_API_SHARED_SECRET: "secret", ETSY_REDIRECT_URI: "https://app.test/api/etsy-callback", ETSY_TOKEN_ENCRYPTION_KEY: Buffer.alloc(32, 3).toString("base64") };
const now = new Date("2026-07-16T20:00:00.000Z");
describe("Etsy OAuth", () => {
  it("creates S256 PKCE and exact read scopes in sealed 15-minute state", () => { const result = beginEtsyAuthorization({ workspaceId: "w", userId: "u", env, now }); const url = new URL(result.authorizeUrl); expect(url.searchParams.get("scope")).toBe("transactions_r shops_r"); expect(result.challenge).toBe(createHash("sha256").update(result.verifier).digest("base64url")); expect(openEtsyAuthorizationContext({ sealedContext: result.sealedContext, returnedState: result.state, workspaceId: "w", userId: "u", env, now: new Date(now.getTime() + 900000) })).toMatchObject({ workspaceId: "w", userId: "u" }); expect(() => openEtsyAuthorizationContext({ sealedContext: result.sealedContext, returnedState: result.state, workspaceId: "w", userId: "u", env, now: new Date(now.getTime() + 900001) })).toThrow("Unable to connect"); });
  it("rejects state and binding mismatches", () => { const result = beginEtsyAuthorization({ workspaceId: "w", userId: "u", env, now }); expect(() => openEtsyAuthorizationContext({ sealedContext: result.sealedContext, returnedState: "wrong", workspaceId: "w", userId: "u", env, now })).toThrow(); expect(() => openEtsyAuthorizationContext({ sealedContext: result.sealedContext, returnedState: result.state, workspaceId: "other", userId: "u", env, now })).toThrow(); });
  it("exchanges and refreshes tokens with redacted errors and expiries", async () => { const fetchImpl = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ access_token: "1.access", refresh_token: "refresh", expires_in: 3600 }) }); const timeoutSignal = { timeout: true }; const createTimeoutSignal = vi.fn(() => timeoutSignal); const token = await exchangeEtsyCallback({ code: "code", verifier: "verifier", env, fetchImpl, now, createTimeoutSignal }); expect(token.accessTokenExpiresAt).toBe("2026-07-16T21:00:00.000Z"); expect(token.refreshTokenExpiresAt).toBe("2026-10-14T20:00:00.000Z"); expect(fetchImpl.mock.calls[0][1].headers["x-api-key"]).toBe("key:secret"); expect(fetchImpl.mock.calls[0][1].signal).toBe(timeoutSignal); await refreshEtsyAuthorization({ workspaceId: "w", refreshToken: "refresh", env, fetchImpl, now, persist: false }); expect(fetchImpl.mock.calls[1][1].body.get("grant_type")).toBe("refresh_token"); expect(fetchImpl.mock.calls[1][1].signal).toBeDefined(); fetchImpl.mockResolvedValueOnce({ ok: false }); await expect(exchangeEtsyCallback({ code: "secret-code", verifier: "v", env, fetchImpl, now })).rejects.toThrow("Unable to connect Etsy shop."); });
  it("maps aborts to a generic redacted connection error", async () => { const fetchImpl = vi.fn().mockRejectedValue(Object.assign(new Error("secret timeout detail"), { name: "AbortError" })); await expect(exchangeEtsyCallback({ code: "secret-code", verifier: "secret-verifier", env, fetchImpl, now, createTimeoutSignal: () => ({}) })).rejects.toMatchObject({ name: "EtsyConnectionError", message: "Unable to connect Etsy shop." }); });
  it("fails refresh when token persistence finds no connection row", async () => { store.update.mockResolvedValueOnce(null); const fetchImpl = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ access_token: "1.access", refresh_token: "refresh", expires_in: 3600 }) }); await expect(refreshEtsyAuthorization({ workspaceId: "missing", refreshToken: "refresh", env, fetchImpl, now, createTimeoutSignal: () => ({}) })).rejects.toMatchObject({ name: "EtsyConnectionError", message: "Unable to connect Etsy shop." }); expect(store.update).toHaveBeenCalledOnce(); });});
